# Generated by Django 4.2.13 on 2024-06-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_curso',
            field=models.ImageField(default=1, upload_to='materiales/'),
            preserve_default=False,
        ),
    ]
