# Generated by Django 4.2.13 on 2024-06-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_curso_imagen_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='es_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
