# Generated by Django 4.2.13 on 2024-06-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='es_instructor',
        ),
        migrations.AlterField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='myapp.instructor'),
        ),
    ]
