# Generated by Django 4.2.13 on 2024-06-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_curso_es_instructor_alter_curso_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='imagen_curso',
        ),
    ]
