# Generated by Django 4.2.13 on 2024-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_respuesta_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='texto',
            field=models.CharField(max_length=257),
        ),
    ]
